# CI de níve  04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inpecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Checando padronizaçao do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependencias
        run: yarn

      - name: Checando padronizaçao do código
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependencias
      - name: Instalando dependências
        run: yarn

      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with:
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy simulation
        run: echo 'Simulando o deploy com suecesso'
